name: BeyondBeta
favicon: null
layout_spectrum: 0.22204
typography_spectrum: 0.33359
title: 'Where the entrepreneur meets the enterprise: Beta & Beyond'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6d6e72'
    - '#949398'
    - '#d8d7dc'
    - '#f9b142'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
