name: BeyondBeta
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26013
title: 'The entrepreneur meets the enterprise and Beta & Beyond'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6d6e72'
    - '#949398'
    - '#d8d7dc'
    - '#f9b142'
  brandStrength: 0.375
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
